module.exports = {
  up: (queryInterface) => {
    const records = [];
    records.push({
      questionId: 17,
      text:
        '<p>Fox Pond is a popular recreation site for swimming, boating, and fishing. The Somerset Department of Recreation organizes a youth swim team at the lake every summer, and a small company rents kayaks on the lake year-round. Visitors can walk to a few nearby businesses that sell lunch and ice cream. During the summer, approximately 250 people visit the public beach on the southern end of Fox Pond each day, and the pond remains a popular attraction even in the colder months.</p><br><p>In addition to being a recreational and economic asset to the people of Somerset, Fox Pond is an important wildlife area. Volunteers from the local chapter of the Audubon Society have recorded over 45 bird species, including some federally threatened and endangered species, stopping at the pond during the fall migration. The pond is home to fish and aquatic invertebrates, and mammals such as red-tailed foxes, muskrat, and black bear have been sighted. Volunteers routinely remove Japanese knotweed (Fallopia japonica) from the pond perimeter, but the pond does not have other significant invasive species concerns. Fox Pond is connected to a number of local streams, including the Saddle River, which was recently daylighted as part of a restoration project.</p><br><p>When HABs occur, humans cannot use the pond due to the presence of toxic microcystins. This restricts recreation during summer – the busiest time of the year – and represents a financial loss to the businesses and town. There are also concerns that small children or pets will ingest pond water during a HAB and become ill.</p><br><p>In addition, the HABs threaten the ecological balance of Fox Pond. There have been at least seven fish kills since the HABs began in 2004, and it is possible that small mammals that drink pond water or eat fish from the pond could have become ill from microcystins. The HABs also compromise downstream water quality, particularly in terms of dissolved oxygen.</p><br><p>The Friends of Fox Pond will collect water quality data twice a week to record conditions in the pond. This will establish a baseline for pond health. If a HAB occurs, sampling will increase to at least every other day for the duration of the bloom. We will share our data with the Town of Somerset’s Board of Health and Conservation Commission, as well as the Massachusetts Department of Environmental Protection, all of whom are interested in improving water quality conditions in the surrounding watershed. Our data will establish typical ranges of the measured parameters and will capture changes in those parameters before, during, and after a bloom.</p>',
    });
    records.push({
      questionId: 18,
      text:
        '<p>This project is focused on harmful algal blooms (HABs) in Fox Pond, located in Somerset, MA. HABs have become increasingly common since 2004, typically lasting approximately one to two months in late summer. This project is designed to document the water quality conditions in Fox Pond before, during, and after HAB occurrences.</p><br><p>The Greater Somerset Watershed Alliance (GSWA) conducted citizen science monitoring of Fox Pond until the organization dissolved in 2015. GSWA confirmed the presence of microcystins in the water during HABs. The group also measured E. coli and water quality parameters such as temperature, dissolved oxygen, conductivity, and pH. This project, led by the Friends of Fox Pond, will continue and build upon their work.</p><br><p>The Friends of Fox Pond hypothesize that the incidence of HABs is related to land use changes in the watershed that have led to more impervious surfaces and increased fertilizer use on residential landscapes. Residential development in the Fox Pond watershed has increased substantially in the past twenty years. In 2007, a 300-home development was constructed in the watershed. State agency staff monitoring local streams have reported increased turbidity and lower dissolved oxygen following the completion of this development, and the Board of Health’s weekly beach monitoring data indicate higher E. coli concentrations.</p><br><p>Friends of Fox Pond will collaborate with the Somerset Board of Health to conduct monitoring that complements their beach water quality testing. Results of the monitoring will be shared with the Conservation Commission to inform stormwater management practices in the Fox Pond watershed. Documentation of HAB episodes will be provided to Massachusetts Department of Environmental Protection for their statewide database.</p>',
    });
    records.push({
      questionId: 19,
      text:
        '<p>Volunteer citizen scientists with the Friends of Fox Pond will conduct water quality monitoring to document conditions in the pond and establish a baseline. This routine monitoring will occur twice a week, with at least two days in between sampling trips. When a harmful algal bloom (HAB) is observed, monitoring will occur at least every other day for the duration of the bloom.</p><br><p>During each sampling trip, volunteers will use a standardized field sheet to record date, time, and field notes such as weather conditions and wildlife. Volunteers will use a multi-parameter probe meter to measure temperature, pH, conductivity, dissolved oxygen, and turbidity at the surface and just above the bottom substrate. These parameters will be measured at 12 monitoring stations distributed across the surface of the lake on a grid pattern, so volunteers will use a small canoe to access some locations. At three stations, they will also collect water samples to be analyzed for the following parameters in a contracted laboratory (Acme Envirolabs) using the stated methods per their laboratory QAPP, provided as an attachment:</p><br><ul><li>Total nitrogen: EPA 353.2</li><li>Total Kjeldahl nitrogen: EPA 351.2</li><li>Ammonia-N: SM 4500-NH3</li><li>Nitrate-Nitrite-N: EPA 353.2</li><li>Total phosphorus: SM 4500-P</li><li>Orthophosphate: USGS 1-4650-03</li><li>E. coli: SM 9223-B</li></ul><br><p>During a HAB event, volunteers will collect the same suite of parameters described above. At the three sampling stations designated for routine E. coli sampling, volunteers will collect additional water samples to be sent to the laboratory for microcystin analysis according to EPA 546 and chlorophyll-a analysis according to EPA 445.0. They will also choose one of the three stations to test for microcystins in the field using the Abraxis Strip Test.</p><br><p>All field data will be recorded on field sheets provided by the Friends of Fox Pond. The field sheets have been designed to complement those used by the Greater Somerset Watershed Alliance so data can be compared across years. Volunteers will enter data into Excel spreadsheets that will be uploaded to a data management system hosted by the Friends of Fox Pond. The Data Manager will create graphs to visualize the measured parameters over time, with attention to trends and aberrations. She will ultimately use regression analysis to explore the relationship between nutrient concentrations and microcystins in Fox Pond. The Chief Scientist will also use ANOVA testing to determine whether there is a statistically significant relationship between dissolved oxygen and chlorophyll-a concentrations.</p>',
    });
    return queryInterface.bulkInsert('Examples', records);
  },

  down: (queryInterface) => queryInterface.bulkDelete('Examples', null, {}),
};
