version: 2
jobs:
  develop-branch:
    docker:
      - image: buildpack-deps:trusty
    environment:
      HEROKU_APP_NAME: turbosap-dev
    steps:
      - checkout
      - run:
          name: $HEROKU_APP_NAME
          command: |
            git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:refs/heads/master

workflows:
  version: 2
  build-deploy-dev:
    jobs:
      - develop-branch:
          filters:
            branches:
              only: develop