version: 2
jobs:
  develop-branch:
    docker:
      - image: buildpack-deps:trusty
    environment:
      HEROKU_APP_NAME: turbosap-dev
    steps:
      - checkout
      - run:
          name: $HEROKU_APP_NAME
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
   
   staging-branch:
    docker:
      - image: buildpack-deps:trusty
    environment:
      HEROKU_APP_NAME: turbosap-stage
    steps:
      - checkout
      - run:
          name: $HEROKU_APP_NAME
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
    
   master-branch:
    docker:
      - image: buildpack-deps:trusty
    environment:
      HEROKU_APP_NAME: turbosap
    steps:
      - checkout
      - run:
          name: $HEROKU_APP_NAME
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
                       
            
          
workflows:
  version: 2
  build-deploy:
    jobs:
      - develop-branch:
          filters:
            branches:
              only: develop
      - staging-branch:
          filters:
            branches:
              only: staging
      - master-branch:
          filters:
            branches:
              only: master